language: node_js

node_js:
  - "stable"

services:
  - docker

git:
  depth: 30

sudo:
  false

cache:
  directories:
    - /tmp/phantomjs

addons:
  firefox: "41.0.1"

before_install:
  # Install CouchDB Master
  - docker run -d -p 3000:5984 klaemo/couchdb:2.0-dev --with-haproxy --with-admin-party-please -n 1

  # Because Saucelabs doesnt proxy 5984 on OSX
  - export COUCH_HOST=http://127.0.0.1:3000

script: npm run $COMMAND

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

    # Workaround for Selenium #3280 issue
  - "sudo sed -i 's/^127\\.0\\.0\\.1.*$/127.0.0.1 localhost/' /etc/hosts"
  
  # Fail early so we dont run hours of saucelabs if we know there
  # is a lint failure
  - npm run jshint

after_failure:
  - "curl -X GET http://127.0.0.1:3000/_log?bytes=1000000"

env:
  matrix:
  - COMMAND=test
  - CLIENT=selenium:firefox COMMAND=test
  - CLIENT=selenium:phantomjs COMMAND=test
  - COMMAND=report-coverage

matrix:
 allow_failures:
 - env: COMMAND=report-coverage
 fast_finish: true

branches:
  only:
  - master
